# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/android:api-28-node
    environment:
      BASH_ENV: "~/.nvm/nvm.sh"
    steps:
      - checkout
      - run:
          name: Install Node 12.10.0
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            source ~/.nvm/nvm.sh
            set +e
            nvm install 12.10.0
      - run: chmod +x script.sh
      - run: ./script.sh
workflows:
  welcome:
    jobs:
      - test